#!/usr/bin/env bash

# Release automation for amazon-mq/rabbitmq-queue-migration.
#
# The release process has a manual gate in the middle (open a PR, wait for
# CI, merge it), so the process is split into subcommands that mirror the
# phases rather than a single monolithic run:
#
#   ./release.sh prepare <version>   # branch, bump version, changelog, PR
#     ... a human merges the PR once CI is green ...
#   ./release.sh tag <version>       # tag the merged commit and push the tag
#   ./release.sh build <version>     # build the .ez plugin archive
#   ./release.sh publish <version>   # create the GitHub release
#
# This script assumes it is run from within a rabbitmq-server 3.13.x clone,
# checked out as deps/rabbitmq_queue_migration. That layout is what lets
# `make DIST_AS_EZS=true dist` build the .ez without a separate server clone.

set -o errexit
set -o nounset
set -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly script_dir

readonly makefile="$script_dir/Makefile"
readonly changelog="$script_dir/CHANGELOG.md"
readonly gh_project="rabbitmq-queue-migration"

# The credit line github_changelog_generator unconditionally appends. There
# is no option to suppress it (verified in the generator source), so we strip
# it after generation.
readonly credit_line_marker="This Changelog was automatically generated by \[github_changelog_generator\]"

readonly red='\033[0;31m'
readonly green='\033[0;32m'
readonly yellow='\033[1;33m'
readonly blue='\033[0;34m'
readonly nc='\033[0m'

declare -i dry_run=0
declare -i assume_yes=0

log_info() {
    echo -e "${blue}[$(date '+%H:%M:%S')]${nc} $1"
}

log_success() {
    echo -e "${green}[$(date '+%H:%M:%S')]${nc} $1"
}

log_warning() {
    echo -e "${yellow}[$(date '+%H:%M:%S')]${nc} WARNING: $1"
}

log_error() {
    echo -e "${red}[$(date '+%H:%M:%S')]${nc} ERROR: $1" >&2
}

# Run a state-changing command, honoring --dry-run. Read-only commands
# (checks, queries) are called directly and always execute so that dry-run
# still validates the environment against real repository state.
run() {
    if (( dry_run ))
    then
        echo -e "${yellow}DRY-RUN:${nc} $*" >&2
    else
        "$@"
    fi
}

# Prompt before an irreversible step unless --yes was given. Reads from
# /dev/tty so it works even when stdin is redirected.
confirm() {
    local -r prompt="$1"

    if (( assume_yes )) || (( dry_run ))
    then
        return 0
    fi

    local reply
    read -r -p "$prompt [y/N] " reply < /dev/tty
    [[ "$reply" == [yY] ]]
}

require_tools() {
    local -a missing=()
    local tool

    for tool in "$@"
    do
        if ! command -v "$tool" > /dev/null 2>&1
        then
            missing+=("$tool")
        fi
    done

    if (( ${#missing[@]} > 0 ))
    then
        log_error "missing required tools: ${missing[*]}"
        exit 1
    fi
}

require_env() {
    local var
    local -a missing=()

    for var in "$@"
    do
        if [[ -z "${!var:-}" ]]
        then
            missing+=("$var")
        fi
    done

    if (( ${#missing[@]} > 0 ))
    then
        log_error "missing required environment variables: ${missing[*]}"
        exit 1
    fi
}

validate_version() {
    local -r version="$1"

    if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
    then
        log_error "version '$version' is not a valid semver (expected MAJOR.MINOR.PATCH)"
        exit 1
    fi
}

require_clean_tree() {
    if [[ -n "$(git -C "$script_dir" status --porcelain)" ]]
    then
        log_error "working tree is not clean; commit or stash changes first"
        exit 1
    fi
}

release_branch() {
    local -r version="$1"
    echo "$gh_project-$version"
}

ez_path() {
    local -r version="$1"
    echo "$script_dir/plugins/${gh_project//-/_}-$version.ez"
}

cmd_prepare() {
    local -r version="$1"

    validate_version "$version"
    require_tools git sed github_changelog_generator gh
    require_env GITHUB_API_TOKEN
    require_clean_tree

    local -r branch="$(release_branch "$version")"

    if git -C "$script_dir" rev-parse --verify --quiet "$branch" > /dev/null
    then
        log_error "branch '$branch' already exists"
        exit 1
    fi

    log_info "Creating release branch $branch"
    run git -C "$script_dir" checkout -b "$branch"

    log_info "Bumping PROJECT_VERSION to $version in Makefile"
    run sed -i.bak "s/^PROJECT_VERSION =.*/PROJECT_VERSION = $version/" "$makefile"
    run rm -f "$makefile.bak"

    # user, project, header, and excluded labels come from the
    # .github_changelog_generator params file in this directory. main() has
    # already cd'd here so the file is picked up and CHANGELOG.md is written
    # in place.
    log_info "Generating CHANGELOG.md for $version"
    run github_changelog_generator \
        --future-release "$version" \
        --token "$GITHUB_API_TOKEN"

    log_info "Removing github_changelog_generator credit line"
    run perl -0pi -e "s/\n*\\\\\\* \\*${credit_line_marker}[^\n]*\\*\n*/\n/" "$changelog"

    log_info "Committing version bump and changelog"
    run git -C "$script_dir" add Makefile CHANGELOG.md
    run git -C "$script_dir" commit -m "$gh_project $version"

    if confirm "Push branch $branch to origin?"
    then
        run git -C "$script_dir" push -u origin "$branch"
    else
        log_warning "Skipped push; run 'git push -u origin $branch' manually"
        return 0
    fi

    if confirm "Open a pull request with 'gh pr create --fill'?"
    then
        run gh pr create --fill
    else
        log_warning "Skipped PR creation"
    fi

    log_success "prepare complete. Merge the PR once CI is green, then run: $0 tag $version"
}

cmd_tag() {
    local -r version="$1"

    validate_version "$version"
    require_tools git gpg
    require_env GPG_KEY_ID

    local -r branch="$(release_branch "$version")"

    log_info "Updating main"
    run git -C "$script_dir" checkout main
    run git -C "$script_dir" pull origin main
    run git -C "$script_dir" remote prune origin

    if git -C "$script_dir" rev-parse --verify --quiet "$branch" > /dev/null
    then
        run git -C "$script_dir" branch -d "$branch"
    fi

    if git -C "$script_dir" rev-parse --verify --quiet "refs/tags/$version" > /dev/null
    then
        log_error "tag '$version' already exists locally"
        exit 1
    fi

    log_info "Creating signed tag $version"
    run git -C "$script_dir" tag \
        --annotate --sign --local-user="$GPG_KEY_ID" \
        --message="$gh_project $version" "$version"

    if confirm "Push tag $version to origin?"
    then
        run git -C "$script_dir" push origin "refs/tags/$version"
    else
        log_warning "Skipped tag push; run 'git push origin refs/tags/$version' manually"
        return 0
    fi

    log_success "tag complete. Next run: $0 build $version"
}

cmd_build() {
    local -r version="$1"

    validate_version "$version"
    require_tools git make
    require_clean_tree

    local head_ref
    head_ref="$(git -C "$script_dir" rev-parse --verify HEAD)"
    local tag_ref
    tag_ref="$(git -C "$script_dir" rev-parse --verify "refs/tags/$version^{commit}" 2>/dev/null || true)"

    if [[ -z "$tag_ref" ]]
    then
        log_error "tag '$version' not found; run '$0 tag $version' first"
        exit 1
    fi

    # The .ez version is derived from git-describe. If HEAD is not exactly the
    # tag, the archive is named with a +dirty/commit suffix and publish would
    # look for the wrong file.
    if [[ "$head_ref" != "$tag_ref" ]]
    then
        log_error "HEAD is not at tag '$version'; checkout the tag before building"
        exit 1
    fi

    log_info "Building .ez archive with 'make DIST_AS_EZS=true dist'"
    run make -C "$script_dir" DIST_AS_EZS=true dist

    local -r ez="$(ez_path "$version")"

    if (( dry_run ))
    then
        log_info "DRY-RUN: would verify $ez exists"
        return 0
    fi

    if [[ ! -f "$ez" ]]
    then
        log_error "expected archive not found: $ez"
        exit 1
    fi

    log_success "build complete: $ez"
}

cmd_publish() {
    local -r version="$1"

    validate_version "$version"
    require_tools gh
    require_env GITHUB_API_TOKEN

    local -r ez="$(ez_path "$version")"

    if (( ! dry_run )) && [[ ! -f "$ez" ]]
    then
        log_error "archive not found: $ez; run '$0 build $version' first"
        exit 1
    fi

    log_info "Publishing GitHub release $version with $ez"

    if confirm "Create GitHub release $version (marks it --latest)?"
    then
        run gh release create "$version" \
            --verify-tag \
            --title "$gh_project $version" \
            --latest \
            --generate-notes \
            "$ez"
    else
        log_warning "Skipped release creation"
        return 0
    fi

    log_success "publish complete. Optionally attach the GitHub milestone to the release."
}

show_usage() {
    cat << EOF
Usage: $0 [--dry-run] [--yes] <command> <version>

Commands:
  prepare <version>   Create release branch, bump PROJECT_VERSION, regenerate
                      CHANGELOG.md, commit, push, and open a PR.
  tag <version>       After the PR merges, update main and create/push the
                      signed release tag.
  build <version>     Build the .ez plugin archive (must be run at the tag).
  publish <version>   Create the GitHub release with the built .ez.

Options:
  --dry-run   Print state-changing commands without executing them.
  --yes       Skip confirmation prompts before irreversible steps.
  -h, --help  Show this help.

Environment:
  GITHUB_API_TOKEN   Required by prepare and publish.
  GPG_KEY_ID         Required by tag (signing key for the annotated tag).

This script must be run from deps/rabbitmq_queue_migration within a
rabbitmq-server 3.13.x clone.
EOF
}

main() {
    cd "$script_dir"

    local -a positional=()

    while (( $# > 0 ))
    do
        case "$1" in
            --dry-run)
                dry_run=1
                shift
                ;;
            --yes)
                assume_yes=1
                shift
                ;;
            -h|--help)
                show_usage
                exit 0
                ;;
            -*)
                log_error "unknown option: $1"
                show_usage
                exit 1
                ;;
            *)
                positional+=("$1")
                shift
                ;;
        esac
    done

    if (( ${#positional[@]} != 2 ))
    then
        show_usage
        exit 1
    fi

    local -r command="${positional[0]}"
    local -r version="${positional[1]}"

    case "$command" in
        prepare)
            cmd_prepare "$version"
            ;;
        tag)
            cmd_tag "$version"
            ;;
        build)
            cmd_build "$version"
            ;;
        publish)
            cmd_publish "$version"
            ;;
        *)
            log_error "unknown command: $command"
            show_usage
            exit 1
            ;;
    esac
}

main "$@"
